#define CSS_STR2(str)	#str
#define CSS_STR(str)	CSS_STR2(str)

#define APPLICATION_NAME	"Cat Socket Server"
#define CAT_REVDATE		"24 January 2015"
#define CAT_VERSION_MAJOR	0
#define CAT_VERSION_MINOR	1
#define CAT_VERSION_PATCH	0
#define CAT_VERSION_REVISION	1
#define CAT_VERSION_RC	""
#define CAT_VERSION		CSS_STR(CAT_VERSION_MAJOR) "." CSS_STR(CAT_VERSION_MINOR) "." \
				CSS_STR(CAT_VERSION_PATCH) CAT_VERSION_RC
#define CAT_REVISION		CSS_STR(CAT_VERSION_REVISION)
